# Generated by Django 2.1.2 on 2018-11-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Estado Lista')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Estado Producto')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Estado Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_productos_agregados', models.IntegerField(verbose_name='Productos Agregados')),
                ('total_productos_comprados', models.IntegerField(verbose_name='Productos Comprados')),
                ('costo_total_presupuestado', models.IntegerField(verbose_name='Total Presupuestado')),
                ('costo_total_real', models.IntegerField(verbose_name='Total Real')),
                ('estadoLista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EstadoLista', verbose_name='Estado Lista')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo_real', models.IntegerField(verbose_name='Costo Real')),
                ('costo_presupuestado', models.IntegerField(verbose_name='Costo Presupuestado')),
                ('notas_adicionales', models.CharField(max_length=200, null=True, verbose_name='Notas Adicionales')),
                ('estadoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EstadoProducto', verbose_name='Estado Producto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lista')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_region', models.IntegerField(unique=True, verbose_name='Nro. Región')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_sucursal', models.CharField(max_length=50, null=True, verbose_name='Nombre Sucursal')),
                ('direccion', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comuna')),
                ('estado_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EstadoTienda', verbose_name='Estado Tienda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
    ]
