# Generated by Django 2.1.2 on 2018-11-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Tienda'),
            preserve_default=False,
        ),
    ]
