# Generated by Django 2.1.2 on 2018-12-07 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20181129_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='nombre_lista',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre Lista'),
        ),
        migrations.AddField(
            model_name='lista',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre Usuario'),
            preserve_default=False,
        ),
    ]
