# Generated by Django 2.1.2 on 2018-12-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181207_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nombre_lista',
            field=models.CharField(max_length=30, verbose_name='Nombre Lista'),
        ),
    ]
