# Generated by Django 2.1.2 on 2018-12-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181210_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='nro_region',
        ),
    ]
